In [11]:
# importando os dados
import pandas as pd

path = r'/home/lapisco/Desktop/ica/ICA/Dados/datasets/regressao/abalone/data.csv'
data = pd.read_csv(path)

data = pd.DataFrame(data)
data

      1  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
0     1  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     2  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     1  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     3  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     3  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  2  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  1  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  1  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  2  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  1  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [12]:
# Pré-processamento
#   Normalizando os dados

from sklearn.preprocessing import MinMaxScaler

normalizador = MinMaxScaler()
normalizador.fit(data)

dados_normalizados = pd.DataFrame(normalizador.transform(data), columns = data.columns)
dados_normalizados.head()

X = dados_normalizados.drop(columns='15')
y = dados_normalizados['15']

XB = data.drop(columns='15')
yB = data['15']

In [13]:
# Separando os dados para o treinamento

from sklearn.model_selection import train_test_split

X_trainB, X_testB, y_trainB, y_testB = train_test_split(XB, yB, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
corr = data.corr()
corr

,1,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15
1,1.000000,-0.449014,-0.458448,-0.418346,-0.461512,-0.441185,-0.454960,-0.445818,-0.351547
0.455,-0.449014,1.000000,0.986813,0.827552,0.925255,0.897905,0.903010,0.897697,0.557123
0.365,-0.458448,0.986813,1.000000,0.833705,0.925452,0.893159,0.899726,0.905328,0.575005
0.095,-0.418346,0.827552,0.833705,1.000000,0.819209,0.774957,0.798293,0.817326,0.558109
0.514,-0.461512,0.925255,0.925452,0.819209,1.000000,0.969403,0.966372,0.955351,0.540818
0.2245,-0.441185,0.897905,0.893159,0.774957,0.969403,1.000000,0.931956,0.882606,0.421256
0.101,-0.454960,0.903010,0.899726,0.798293,0.966372,0.931956,1.000000,0.907647,0.504274
0.15,-0.445818,0.897697,0.905328,0.817326,0.955351,0.882606,0.907647,1.000000,0.628031
15,-0.351547,0.557123,0.575005,0.558109,0.540818,0.421256,0.504274,0.628031,1.000000

### Regressão Multipla

In [15]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lrB = LinearRegression()

lr.fit(X_train, y_train)
lrB.fit(X_trainB, y_trainB)

r = lr.score(X_test, y_test)
rB = lrB.score(X_testB, y_testB)

print('',"-"*50, '\nCom Normalização: r = ', r, '\n', '-'*50, '\nSem Normalização: rB = ', rB, '\n', '-'*50)

 --------------------------------------------------
Com Normalização: r =  0.5752448821249408
 --------------------------------------------------
Sem Normalização: rB =  0.5752448821249398
 --------------------------------------------------

### Regressão Simples

In [16]:
import numpy as np 

X = dados_normalizados['0.365']
y = dados_normalizados['0.455']

X = np.reshape(X, (-1,1))
y = np.reshape(y, (-1,1))

XB = data['0.365']
yB = data['0.455']

XB = np.reshape(XB, (-1,1))
yB = np.reshape(yB, (-1,1))
# Separando os dados para o treinamento

from sklearn.model_selection import train_test_split

X_trainB, X_testB, y_trainB, y_testB = train_test_split(XB, yB, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lrB = LinearRegression()

lr.fit(X_train, y_train)
lrB.fit(X_trainB, y_trainB)

r = lr.score(X_test, y_test)
rB = lrB.score(X_testB, y_testB)

print('',"-"*50, '\nCom Normalização: r = ', r, '\n', '-'*50, '\nSem Normalização: rB = ', rB, '\n', '-'*50)

 --------------------------------------------------
Com Normalização: r =  0.9743717518002528
 --------------------------------------------------
Sem Normalização: rB =  0.9743717518002528
 --------------------------------------------------

### SVR

In [18]:
from sklearn.preprocessing import MinMaxScaler

X = dados_normalizados['0.365']
y = dados_normalizados['0.455']

X = np.reshape(X, (-1,1))
y = np.reshape(y, (-1,1)).ravel()

XB = data['0.365']
yB = data['0.455']

XB = np.reshape(XB, (-1,1))
yB = np.reshape(yB, (-1,1)).ravel()
# Separando os dados para o treinamento


from sklearn.model_selection import train_test_split

X_trainB, X_testB, y_trainB, y_testB = train_test_split(XB, yB, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
from sklearn.svm import SVR

svr = SVR(kernel= 'linear')
svrB = SVR(kernel= 'linear')

svr.fit(X_train, y_train)
svrB.fit(X_trainB, y_trainB)


r = svr.score(X_test, y_test)
rB = svrB.score(X_testB, y_testB)

print('',"-"*50, '\nCom Normalização: r = ', r, '\n', '-'*50, '\nSem Normalização: rB = ', rB, '\n', '-'*50)

 --------------------------------------------------
Com Normalização: r =  0.9646929316621623
 --------------------------------------------------
Sem Normalização: rB =  0.9390405446425155
 --------------------------------------------------